/*
 * generated by Xtext 2.26.0
 */
package de.dlr.sc.virsat.model.ext.tml.structural.declaration.ui;

import com.google.inject.Injector;
import de.dlr.sc.virsat.model.ext.tml.structural.declaration.enumdefinition.ui.internal.EnumdefinitionActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EnumDefinitionExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(EnumdefinitionActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		EnumdefinitionActivator activator = EnumdefinitionActivator.getInstance();
		return activator != null ? activator.getInjector(EnumdefinitionActivator.DE_DLR_SC_VIRSAT_MODEL_EXT_TML_STRUCTURAL_DECLARATION_ENUMDEFINITION) : null;
	}

}
