/*
 * generated by Xtext 2.26.0
 */
package de.dlr.sc.virsat.model.ext.tml.structural.declaration.serializer;

import com.google.inject.Inject;
import de.dlr.sc.virsat.model.ext.tml.structural.declaration.services.TaskDefinitionGrammarAccess;
import de.dlr.sc.virsat.model.ext.tml.structural.serializer.DeclarationLangaugeSemanticSequencer;
import de.dlr.sc.virsat.model.ext.tml.structural.structural.ArrayDimension;
import de.dlr.sc.virsat.model.ext.tml.structural.structural.Attribute;
import de.dlr.sc.virsat.model.ext.tml.structural.structural.StructuralPackage;
import de.dlr.sc.virsat.model.ext.tml.structural.structural.TaskDefinition;
import de.dlr.sc.virsat.model.ext.tml.structural.structural.TaskInputDefinition;
import de.dlr.sc.virsat.model.ext.tml.structural.structural.TaskOutputDefinition;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;

@SuppressWarnings("all")
public class TaskDefinitionSemanticSequencer extends DeclarationLangaugeSemanticSequencer {

	@Inject
	private TaskDefinitionGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == StructuralPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case StructuralPackage.ARRAY_DIMENSION:
				sequence_ArrayDimension(context, (ArrayDimension) semanticObject); 
				return; 
			case StructuralPackage.ATTRIBUTE:
				sequence_Attribute(context, (Attribute) semanticObject); 
				return; 
			case StructuralPackage.TASK_DEFINITION:
				sequence_TaskDefinition(context, (TaskDefinition) semanticObject); 
				return; 
			case StructuralPackage.TASK_INPUT_DEFINITION:
				sequence_TaskInputDefinition(context, (TaskInputDefinition) semanticObject); 
				return; 
			case StructuralPackage.TASK_OUTPUT_DEFINITION:
				sequence_TaskOutputDefinition(context, (TaskOutputDefinition) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     TaskDefinition returns TaskDefinition
	 *
	 * Constraint:
	 *     ((outputs+=TaskOutputDefinition | parameters+=Attribute)? (name=EString inputs+=TaskInputDefinition*)?)+
	 * </pre>
	 */
	protected void sequence_TaskDefinition(ISerializationContext context, TaskDefinition semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TaskInputDefinition returns TaskInputDefinition
	 *
	 * Constraint:
	 *     (name=EString dataType=[DataType|FQN]?)
	 * </pre>
	 */
	protected void sequence_TaskInputDefinition(ISerializationContext context, TaskInputDefinition semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     TaskOutputDefinition returns TaskOutputDefinition
	 *
	 * Constraint:
	 *     (name=EString dataType=[DataType|FQN]?)
	 * </pre>
	 */
	protected void sequence_TaskOutputDefinition(ISerializationContext context, TaskOutputDefinition semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
