/*
 * generated by Xtext 2.26.0
 */
package de.dlr.sc.virsat.model.ext.tml.structural.declaration.parser.antlr;

import com.google.inject.Inject;
import de.dlr.sc.virsat.model.ext.tml.structural.declaration.parser.antlr.internal.InternalEnumDefinitionParser;
import de.dlr.sc.virsat.model.ext.tml.structural.declaration.services.EnumDefinitionGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class EnumDefinitionParser extends AbstractAntlrParser {

	@Inject
	private EnumDefinitionGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalEnumDefinitionParser createParser(XtextTokenStream stream) {
		return new InternalEnumDefinitionParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Enumeration";
	}

	public EnumDefinitionGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EnumDefinitionGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
