/*
 * generated by Xtext 2.26.0
 */
package de.dlr.sc.virsat.model.ext.tml.behavioral.ui;

import com.google.inject.Injector;
import de.dlr.sc.virsat.model.ext.tml.behavioral.channeldefinition.ui.internal.ChanneldefinitionActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ChannelDefinitionExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(ChanneldefinitionActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		ChanneldefinitionActivator activator = ChanneldefinitionActivator.getInstance();
		return activator != null ? activator.getInjector(ChanneldefinitionActivator.DE_DLR_SC_VIRSAT_MODEL_EXT_TML_BEHAVIORAL_CHANNELDEFINITION) : null;
	}

}
