/*
 * generated by Xtext 2.26.0
 */
package de.dlr.sc.virsat.model.ext.tml.structural.declaration.parser.antlr;

import com.google.inject.Inject;
import de.dlr.sc.virsat.model.ext.tml.structural.declaration.parser.antlr.internal.InternalTaskDefinitionParser;
import de.dlr.sc.virsat.model.ext.tml.structural.declaration.services.TaskDefinitionGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class TaskDefinitionParser extends AbstractAntlrParser {

	@Inject
	private TaskDefinitionGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTaskDefinitionParser createParser(XtextTokenStream stream) {
		return new InternalTaskDefinitionParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "TaskDefinition";
	}

	public TaskDefinitionGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TaskDefinitionGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
