/*
 * generated by Xtext 2.26.0
 */
package de.dlr.sc.virsat.model.ext.tml.structural.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.UnorderedGroup;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class DeclarationLangaugeGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class AttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.dlr.sc.virsat.model.ext.tml.structural.DeclarationLangauge.Attribute");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cIsConstAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cIsConstConstKeyword_0_0 = (Keyword)cIsConstAssignment_0.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTypeOfAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cTypeOfITypeCrossReference_3_0 = (CrossReference)cTypeOfAssignment_3.eContents().get(0);
		private final RuleCall cTypeOfITypeFQNParserRuleCall_3_0_1 = (RuleCall)cTypeOfITypeCrossReference_3_0.eContents().get(1);
		private final Assignment cDimensionsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDimensionsArrayDimensionParserRuleCall_4_0 = (RuleCall)cDimensionsAssignment_4.eContents().get(0);
		private final Alternatives cAlternatives_5 = (Alternatives)cGroup.eContents().get(5);
		private final Group cGroup_5_0 = (Group)cAlternatives_5.eContents().get(0);
		private final Keyword cEqualsSignKeyword_5_0_0 = (Keyword)cGroup_5_0.eContents().get(0);
		private final Assignment cValueLiteralAssignment_5_0_1 = (Assignment)cGroup_5_0.eContents().get(1);
		private final RuleCall cValueLiteralEStringParserRuleCall_5_0_1_0 = (RuleCall)cValueLiteralAssignment_5_0_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_5_0_2 = (Keyword)cGroup_5_0.eContents().get(2);
		private final Keyword cSemicolonKeyword_5_1 = (Keyword)cAlternatives_5.eContents().get(1);
		private final UnorderedGroup cUnorderedGroup_5_2 = (UnorderedGroup)cAlternatives_5.eContents().get(2);
		private final Group cGroup_5_2_0 = (Group)cUnorderedGroup_5_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_2_0_0 = (Keyword)cGroup_5_2_0.eContents().get(0);
		private final Group cGroup_5_2_0_1 = (Group)cGroup_5_2_0.eContents().get(1);
		private final Keyword cValueKeyword_5_2_0_1_0 = (Keyword)cGroup_5_2_0_1.eContents().get(0);
		private final Keyword cColonKeyword_5_2_0_1_1 = (Keyword)cGroup_5_2_0_1.eContents().get(1);
		private final Assignment cValueLiteralAssignment_5_2_0_1_2 = (Assignment)cGroup_5_2_0_1.eContents().get(2);
		private final RuleCall cValueLiteralEStringParserRuleCall_5_2_0_1_2_0 = (RuleCall)cValueLiteralAssignment_5_2_0_1_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_5_2_0_1_3 = (Keyword)cGroup_5_2_0_1.eContents().get(3);
		private final Group cGroup_5_2_1 = (Group)cUnorderedGroup_5_2.eContents().get(1);
		private final Keyword cMaxKeyword_5_2_1_0 = (Keyword)cGroup_5_2_1.eContents().get(0);
		private final Keyword cColonKeyword_5_2_1_1 = (Keyword)cGroup_5_2_1.eContents().get(1);
		private final Assignment cMaxValueLiteralAssignment_5_2_1_2 = (Assignment)cGroup_5_2_1.eContents().get(2);
		private final RuleCall cMaxValueLiteralEStringParserRuleCall_5_2_1_2_0 = (RuleCall)cMaxValueLiteralAssignment_5_2_1_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_5_2_1_3 = (Keyword)cGroup_5_2_1.eContents().get(3);
		private final Group cGroup_5_2_2 = (Group)cUnorderedGroup_5_2.eContents().get(2);
		private final Keyword cMinKeyword_5_2_2_0 = (Keyword)cGroup_5_2_2.eContents().get(0);
		private final Keyword cColonKeyword_5_2_2_1 = (Keyword)cGroup_5_2_2.eContents().get(1);
		private final Assignment cMinValueLiteralAssignment_5_2_2_2 = (Assignment)cGroup_5_2_2.eContents().get(2);
		private final RuleCall cMinValueLiteralEStringParserRuleCall_5_2_2_2_0 = (RuleCall)cMinValueLiteralAssignment_5_2_2_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_5_2_2_3 = (Keyword)cGroup_5_2_2.eContents().get(3);
		private final Group cGroup_5_2_3 = (Group)cUnorderedGroup_5_2.eContents().get(3);
		private final Keyword cReferenceFrameKeyword_5_2_3_0 = (Keyword)cGroup_5_2_3.eContents().get(0);
		private final Keyword cColonKeyword_5_2_3_1 = (Keyword)cGroup_5_2_3.eContents().get(1);
		private final Assignment cReferenceFrameAssignment_5_2_3_2 = (Assignment)cGroup_5_2_3.eContents().get(2);
		private final CrossReference cReferenceFrameReferenceFrameDefinitionCrossReference_5_2_3_2_0 = (CrossReference)cReferenceFrameAssignment_5_2_3_2.eContents().get(0);
		private final RuleCall cReferenceFrameReferenceFrameDefinitionFQNParserRuleCall_5_2_3_2_0_1 = (RuleCall)cReferenceFrameReferenceFrameDefinitionCrossReference_5_2_3_2_0.eContents().get(1);
		private final Keyword cSemicolonKeyword_5_2_3_3 = (Keyword)cGroup_5_2_3.eContents().get(3);
		private final Group cGroup_5_2_4 = (Group)cUnorderedGroup_5_2.eContents().get(4);
		private final Group cGroup_5_2_4_0 = (Group)cGroup_5_2_4.eContents().get(0);
		private final Keyword cUnitKeyword_5_2_4_0_0 = (Keyword)cGroup_5_2_4_0.eContents().get(0);
		private final Keyword cColonKeyword_5_2_4_0_1 = (Keyword)cGroup_5_2_4_0.eContents().get(1);
		private final Assignment cTypeUnitAssignment_5_2_4_0_2 = (Assignment)cGroup_5_2_4_0.eContents().get(2);
		private final CrossReference cTypeUnitUnitDefinitionCrossReference_5_2_4_0_2_0 = (CrossReference)cTypeUnitAssignment_5_2_4_0_2.eContents().get(0);
		private final RuleCall cTypeUnitUnitDefinitionFQNParserRuleCall_5_2_4_0_2_0_1 = (RuleCall)cTypeUnitUnitDefinitionCrossReference_5_2_4_0_2_0.eContents().get(1);
		private final Keyword cSemicolonKeyword_5_2_4_0_3 = (Keyword)cGroup_5_2_4_0.eContents().get(3);
		private final Keyword cRightCurlyBracketKeyword_5_2_4_1 = (Keyword)cGroup_5_2_4.eContents().get(1);
		private final Keyword cSemicolonKeyword_5_2_4_2 = (Keyword)cGroup_5_2_4.eContents().get(2);
		
		//Attribute returns Attribute:
		//    (isConst?='const')? name=EString ':' typeOf=[IType|FQN] (dimensions+=ArrayDimension)* (('=' valueLiteral=EString';') | (';') |
		//    ('{'
		//        ('value'':' valueLiteral=EString ';')?  &
		//        ('max'':' maxValueLiteral=EString ';')?  &
		//        ('min'':' minValueLiteral=EString ';')?  &
		//        ('referenceFrame'':' referenceFrame=[ReferenceFrameDefinition|FQN] ';')?  &
		//        ('unit'':' typeUnit=[UnitDefinition|FQN] ';')?
		//    '}' ';')? );
		@Override public ParserRule getRule() { return rule; }
		
		//(isConst?='const')? name=EString ':' typeOf=[IType|FQN] (dimensions+=ArrayDimension)* (('=' valueLiteral=EString';') | (';') |
		//('{'
		//    ('value'':' valueLiteral=EString ';')?  &
		//    ('max'':' maxValueLiteral=EString ';')?  &
		//    ('min'':' minValueLiteral=EString ';')?  &
		//    ('referenceFrame'':' referenceFrame=[ReferenceFrameDefinition|FQN] ';')?  &
		//    ('unit'':' typeUnit=[UnitDefinition|FQN] ';')?
		//'}' ';')? )
		public Group getGroup() { return cGroup; }
		
		//(isConst?='const')?
		public Assignment getIsConstAssignment_0() { return cIsConstAssignment_0; }
		
		//'const'
		public Keyword getIsConstConstKeyword_0_0() { return cIsConstConstKeyword_0_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//':'
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//typeOf=[IType|FQN]
		public Assignment getTypeOfAssignment_3() { return cTypeOfAssignment_3; }
		
		//[IType|FQN]
		public CrossReference getTypeOfITypeCrossReference_3_0() { return cTypeOfITypeCrossReference_3_0; }
		
		//FQN
		public RuleCall getTypeOfITypeFQNParserRuleCall_3_0_1() { return cTypeOfITypeFQNParserRuleCall_3_0_1; }
		
		//(dimensions+=ArrayDimension)*
		public Assignment getDimensionsAssignment_4() { return cDimensionsAssignment_4; }
		
		//ArrayDimension
		public RuleCall getDimensionsArrayDimensionParserRuleCall_4_0() { return cDimensionsArrayDimensionParserRuleCall_4_0; }
		
		//(('=' valueLiteral=EString';') | (';') |
		//   ('{'
		//       ('value'':' valueLiteral=EString ';')?  &
		//       ('max'':' maxValueLiteral=EString ';')?  &
		//       ('min'':' minValueLiteral=EString ';')?  &
		//       ('referenceFrame'':' referenceFrame=[ReferenceFrameDefinition|FQN] ';')?  &
		//       ('unit'':' typeUnit=[UnitDefinition|FQN] ';')?
		//   '}' ';')? )
		public Alternatives getAlternatives_5() { return cAlternatives_5; }
		
		//('=' valueLiteral=EString';')
		public Group getGroup_5_0() { return cGroup_5_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_5_0_0() { return cEqualsSignKeyword_5_0_0; }
		
		//valueLiteral=EString
		public Assignment getValueLiteralAssignment_5_0_1() { return cValueLiteralAssignment_5_0_1; }
		
		//EString
		public RuleCall getValueLiteralEStringParserRuleCall_5_0_1_0() { return cValueLiteralEStringParserRuleCall_5_0_1_0; }
		
		//';'
		public Keyword getSemicolonKeyword_5_0_2() { return cSemicolonKeyword_5_0_2; }
		
		//(';')
		public Keyword getSemicolonKeyword_5_1() { return cSemicolonKeyword_5_1; }
		
		//('{'
		//    ('value'':' valueLiteral=EString ';')?  &
		//    ('max'':' maxValueLiteral=EString ';')?  &
		//    ('min'':' minValueLiteral=EString ';')?  &
		//    ('referenceFrame'':' referenceFrame=[ReferenceFrameDefinition|FQN] ';')?  &
		//    ('unit'':' typeUnit=[UnitDefinition|FQN] ';')?
		//'}' ';')?
		public UnorderedGroup getUnorderedGroup_5_2() { return cUnorderedGroup_5_2; }
		
		//'{'
		//        ('value'':' valueLiteral=EString ';')?
		public Group getGroup_5_2_0() { return cGroup_5_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_2_0_0() { return cLeftCurlyBracketKeyword_5_2_0_0; }
		
		//('value'':' valueLiteral=EString ';')?
		public Group getGroup_5_2_0_1() { return cGroup_5_2_0_1; }
		
		//'value'
		public Keyword getValueKeyword_5_2_0_1_0() { return cValueKeyword_5_2_0_1_0; }
		
		//':'
		public Keyword getColonKeyword_5_2_0_1_1() { return cColonKeyword_5_2_0_1_1; }
		
		//valueLiteral=EString
		public Assignment getValueLiteralAssignment_5_2_0_1_2() { return cValueLiteralAssignment_5_2_0_1_2; }
		
		//EString
		public RuleCall getValueLiteralEStringParserRuleCall_5_2_0_1_2_0() { return cValueLiteralEStringParserRuleCall_5_2_0_1_2_0; }
		
		//';'
		public Keyword getSemicolonKeyword_5_2_0_1_3() { return cSemicolonKeyword_5_2_0_1_3; }
		
		//('max'':' maxValueLiteral=EString ';')?
		public Group getGroup_5_2_1() { return cGroup_5_2_1; }
		
		//'max'
		public Keyword getMaxKeyword_5_2_1_0() { return cMaxKeyword_5_2_1_0; }
		
		//':'
		public Keyword getColonKeyword_5_2_1_1() { return cColonKeyword_5_2_1_1; }
		
		//maxValueLiteral=EString
		public Assignment getMaxValueLiteralAssignment_5_2_1_2() { return cMaxValueLiteralAssignment_5_2_1_2; }
		
		//EString
		public RuleCall getMaxValueLiteralEStringParserRuleCall_5_2_1_2_0() { return cMaxValueLiteralEStringParserRuleCall_5_2_1_2_0; }
		
		//';'
		public Keyword getSemicolonKeyword_5_2_1_3() { return cSemicolonKeyword_5_2_1_3; }
		
		//('min'':' minValueLiteral=EString ';')?
		public Group getGroup_5_2_2() { return cGroup_5_2_2; }
		
		//'min'
		public Keyword getMinKeyword_5_2_2_0() { return cMinKeyword_5_2_2_0; }
		
		//':'
		public Keyword getColonKeyword_5_2_2_1() { return cColonKeyword_5_2_2_1; }
		
		//minValueLiteral=EString
		public Assignment getMinValueLiteralAssignment_5_2_2_2() { return cMinValueLiteralAssignment_5_2_2_2; }
		
		//EString
		public RuleCall getMinValueLiteralEStringParserRuleCall_5_2_2_2_0() { return cMinValueLiteralEStringParserRuleCall_5_2_2_2_0; }
		
		//';'
		public Keyword getSemicolonKeyword_5_2_2_3() { return cSemicolonKeyword_5_2_2_3; }
		
		//('referenceFrame'':' referenceFrame=[ReferenceFrameDefinition|FQN] ';')?
		public Group getGroup_5_2_3() { return cGroup_5_2_3; }
		
		//'referenceFrame'
		public Keyword getReferenceFrameKeyword_5_2_3_0() { return cReferenceFrameKeyword_5_2_3_0; }
		
		//':'
		public Keyword getColonKeyword_5_2_3_1() { return cColonKeyword_5_2_3_1; }
		
		//referenceFrame=[ReferenceFrameDefinition|FQN]
		public Assignment getReferenceFrameAssignment_5_2_3_2() { return cReferenceFrameAssignment_5_2_3_2; }
		
		//[ReferenceFrameDefinition|FQN]
		public CrossReference getReferenceFrameReferenceFrameDefinitionCrossReference_5_2_3_2_0() { return cReferenceFrameReferenceFrameDefinitionCrossReference_5_2_3_2_0; }
		
		//FQN
		public RuleCall getReferenceFrameReferenceFrameDefinitionFQNParserRuleCall_5_2_3_2_0_1() { return cReferenceFrameReferenceFrameDefinitionFQNParserRuleCall_5_2_3_2_0_1; }
		
		//';'
		public Keyword getSemicolonKeyword_5_2_3_3() { return cSemicolonKeyword_5_2_3_3; }
		
		//    ('unit'':' typeUnit=[UnitDefinition|FQN] ';')?
		//'}' ';'
		public Group getGroup_5_2_4() { return cGroup_5_2_4; }
		
		//('unit'':' typeUnit=[UnitDefinition|FQN] ';')?
		public Group getGroup_5_2_4_0() { return cGroup_5_2_4_0; }
		
		//'unit'
		public Keyword getUnitKeyword_5_2_4_0_0() { return cUnitKeyword_5_2_4_0_0; }
		
		//':'
		public Keyword getColonKeyword_5_2_4_0_1() { return cColonKeyword_5_2_4_0_1; }
		
		//typeUnit=[UnitDefinition|FQN]
		public Assignment getTypeUnitAssignment_5_2_4_0_2() { return cTypeUnitAssignment_5_2_4_0_2; }
		
		//[UnitDefinition|FQN]
		public CrossReference getTypeUnitUnitDefinitionCrossReference_5_2_4_0_2_0() { return cTypeUnitUnitDefinitionCrossReference_5_2_4_0_2_0; }
		
		//FQN
		public RuleCall getTypeUnitUnitDefinitionFQNParserRuleCall_5_2_4_0_2_0_1() { return cTypeUnitUnitDefinitionFQNParserRuleCall_5_2_4_0_2_0_1; }
		
		//';'
		public Keyword getSemicolonKeyword_5_2_4_0_3() { return cSemicolonKeyword_5_2_4_0_3; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_2_4_1() { return cRightCurlyBracketKeyword_5_2_4_1; }
		
		//';'
		public Keyword getSemicolonKeyword_5_2_4_2() { return cSemicolonKeyword_5_2_4_2; }
	}
	public class ArrayDimensionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.dlr.sc.virsat.model.ext.tml.structural.DeclarationLangauge.ArrayDimension");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cSizeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cSizeEIntParserRuleCall_1_0 = (RuleCall)cSizeAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCommaKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Keyword cNameKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Keyword cEqualsSignKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		private final Assignment cNameAssignment_2_3 = (Assignment)cGroup_2.eContents().get(3);
		private final RuleCall cNameEStringParserRuleCall_2_3_0 = (RuleCall)cNameAssignment_2_3.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//ArrayDimension returns ArrayDimension:
		//    '['size=EInt(',''name''='name=EString)?']'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'['size=EInt(',''name''='name=EString)?']'
		public Group getGroup() { return cGroup; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_0() { return cLeftSquareBracketKeyword_0; }
		
		//size=EInt
		public Assignment getSizeAssignment_1() { return cSizeAssignment_1; }
		
		//EInt
		public RuleCall getSizeEIntParserRuleCall_1_0() { return cSizeEIntParserRuleCall_1_0; }
		
		//(',''name''='name=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//','
		public Keyword getCommaKeyword_2_0() { return cCommaKeyword_2_0; }
		
		//'name'
		public Keyword getNameKeyword_2_1() { return cNameKeyword_2_1; }
		
		//'='
		public Keyword getEqualsSignKeyword_2_2() { return cEqualsSignKeyword_2_2; }
		
		//name=EString
		public Assignment getNameAssignment_2_3() { return cNameAssignment_2_3; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_3_0() { return cNameEStringParserRuleCall_2_3_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_3() { return cRightSquareBracketKeyword_3; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.dlr.sc.virsat.model.ext.tml.structural.DeclarationLangauge.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.dlr.sc.virsat.model.ext.tml.structural.DeclarationLangauge.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class FQNElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.dlr.sc.virsat.model.ext.tml.structural.DeclarationLangauge.FQN");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//FQN : ID('.'ID)*;
		@Override public ParserRule getRule() { return rule; }
		
		//ID('.'ID)*
		public Group getGroup() { return cGroup; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }
		
		//('.'ID)*
		public Group getGroup_1() { return cGroup_1; }
		
		//'.'
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}
	
	
	private final AttributeElements pAttribute;
	private final ArrayDimensionElements pArrayDimension;
	private final EStringElements pEString;
	private final EIntElements pEInt;
	private final FQNElements pFQN;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public DeclarationLangaugeGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pAttribute = new AttributeElements();
		this.pArrayDimension = new ArrayDimensionElements();
		this.pEString = new EStringElements();
		this.pEInt = new EIntElements();
		this.pFQN = new FQNElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("de.dlr.sc.virsat.model.ext.tml.structural.DeclarationLangauge".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Attribute returns Attribute:
	//    (isConst?='const')? name=EString ':' typeOf=[IType|FQN] (dimensions+=ArrayDimension)* (('=' valueLiteral=EString';') | (';') |
	//    ('{'
	//        ('value'':' valueLiteral=EString ';')?  &
	//        ('max'':' maxValueLiteral=EString ';')?  &
	//        ('min'':' minValueLiteral=EString ';')?  &
	//        ('referenceFrame'':' referenceFrame=[ReferenceFrameDefinition|FQN] ';')?  &
	//        ('unit'':' typeUnit=[UnitDefinition|FQN] ';')?
	//    '}' ';')? );
	public AttributeElements getAttributeAccess() {
		return pAttribute;
	}
	
	public ParserRule getAttributeRule() {
		return getAttributeAccess().getRule();
	}
	
	//ArrayDimension returns ArrayDimension:
	//    '['size=EInt(',''name''='name=EString)?']'
	//;
	public ArrayDimensionElements getArrayDimensionAccess() {
		return pArrayDimension;
	}
	
	public ParserRule getArrayDimensionRule() {
		return getArrayDimensionAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//EInt returns ecore::EInt:
	//    '-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//FQN : ID('.'ID)*;
	public FQNElements getFQNAccess() {
		return pFQN;
	}
	
	public ParserRule getFQNRule() {
		return getFQNAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
