/*
 * generated by Xtext 2.22.0
 */
package de.dlr.sc.virsat.model.ext.tml.structural.declaration.scoping;

import de.dlr.sc.virsat.model.ext.tml.structural.scoping.DeclarationLangaugeScopeProvider;

public abstract class AbstractDatatypeDefinitionScopeProvider extends DeclarationLangaugeScopeProvider {
}
