<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="structural" nsURI="http://www.virsat.sc.dlr.de/dmf/v1.2/structural"
    nsPrefix="dmf_structural">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="dmf_behavioral" value="../../de.dlr.sc.virsat.model.ext.tml.behavioral/concept/concept.ecore#/"/>
    <details key="dvlm_dmf" value="../../de.dlr.sc.virsat.model/model/dvlm.ecore#//dmf"/>
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="TaskingEnvironment" eSuperTypes="../../de.dlr.sc.virsat.model/model/dvlm.ecore#//dmf/DObject">
    <eAnnotations source="gmf.diagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taskDefinitions" upperBound="-1"
        eType="#//TaskDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="basicTypeDefinitions" upperBound="-1"
        eType="#//BasicTypeDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceFrames" upperBound="-1"
        eType="#//ReferenceFrameDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="units" upperBound="-1"
        eType="#//UnitDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="channelBehaviorDefinitions"
        upperBound="-1" eType="ecore:EClass ../../de.dlr.sc.virsat.model.ext.tml.behavioral/concept/concept.ecore#//ChannelBehaviorDefinition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        eType="#//TaskInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="channels" upperBound="-1"
        eType="#//Channel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeEvents" upperBound="-1"
        eType="#//TimeEvent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataTypes" upperBound="-1"
        eType="#//DataType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumerations" upperBound="-1"
        eType="#//Enumeration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalParameters" upperBound="-1"
        eType="#//Attribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IEventSource" eSuperTypes="../../de.dlr.sc.virsat.model/model/dvlm.ecore#//dmf/DObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
        eType="#//TaskInput">
      <eAnnotations source="gmf.link">
        <details key="style" value="dash"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IType" eSuperTypes="../../de.dlr.sc.virsat.model/model/dvlm.ecore#//dmf/DObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="TaskDefinition" eSuperTypes="../../de.dlr.sc.virsat.model/model/dvlm.ecore#//dmf/DObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
        eType="#//TaskInputDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" upperBound="-1"
        eType="#//TaskOutputDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Attribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serializedDefinition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskInputDefinition" eSuperTypes="../../de.dlr.sc.virsat.model/model/dvlm.ecore#//dmf/DObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataType" eType="#//DataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskOutputDefinition" eSuperTypes="../../de.dlr.sc.virsat.model/model/dvlm.ecore#//dmf/DObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataType" eType="#//DataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicTypeDefinition" eSuperTypes="../../de.dlr.sc.virsat.model/model/dvlm.ecore#//dmf/DObject #//IType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueType" eType="#//EnumValueType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="customSource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnumValueType">
    <eLiterals name="INTEGER" value="1"/>
    <eLiterals name="FLOAT" value="2"/>
    <eLiterals name="STRING" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceFrameDefinition" eSuperTypes="../../de.dlr.sc.virsat.model/model/dvlm.ecore#//dmf/DObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnitDefinition" eSuperTypes="../../de.dlr.sc.virsat.model/model/dvlm.ecore#//dmf/DObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="TaskInstance" eSuperTypes="../../de.dlr.sc.virsat.model/model/dvlm.ecore#//dmf/DObject">
    <eAnnotations source="gmf.node">
      <details key="figure" value="rectangle"/>
      <details key="size" value="150,150"/>
      <details key="color" value="204,229,255"/>
      <details key="border.color" value="18,158,8"/>
      <details key="label" value="name"/>
      <details key="label.readOnly" value="true"/>
      <details key="label.icon" value="false"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeOf" eType="#//TaskDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taskBehavior" eType="ecore:EClass ../../de.dlr.sc.virsat.model.ext.tml.behavioral/concept/concept.ecore#//TaskBehavior"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" upperBound="-1"
        eType="#//TaskOutput" containment="true">
      <eAnnotations source="gmf.affixed"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
        eType="#//TaskInput" containment="true">
      <eAnnotations source="gmf.affixed"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskInput" eSuperTypes="../../de.dlr.sc.virsat.model/model/dvlm.ecore#//dmf/DObject">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="label.placement" value="external"/>
      <details key="label.icon" value="false"/>
      <details key="size" value="20,20"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeOf" eType="#//TaskInputDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" eType="#//IEventSource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="activationThreshold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isFinal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskOutput" eSuperTypes="../../de.dlr.sc.virsat.model/model/dvlm.ecore#//dmf/DObject">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="label.placement" value="external"/>
      <details key="label.icon" value="false"/>
      <details key="size" value="20,20"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeOf" eType="#//TaskOutputDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="channels" upperBound="-1"
        eType="#//Channel">
      <eAnnotations source="gmf.link">
        <details key="style" value="dash"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeEvent" eSuperTypes="../../de.dlr.sc.virsat.model/model/dvlm.ecore#//dmf/DObject #//IEventSource">
    <eAnnotations source="gmf.node">
      <details key="size" value="40,20"/>
      <details key="label" value="name"/>
      <details key="label.placement" value="external"/>
      <details key="label.icon" value="false"/>
      <details key="color" value="0,128,0"/>
      <details key="label.readOnly" value="false"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Channel" eSuperTypes="../../de.dlr.sc.virsat.model/model/dvlm.ecore#//dmf/DObject #//IEventSource">
    <eAnnotations source="gmf.node">
      <details key="size" value="40,20"/>
      <details key="label" value="name"/>
      <details key="label.placement" value="external"/>
      <details key="label.icon" value="false"/>
      <details key="color" value="0,128,0"/>
      <details key="label.readOnly" value="true"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataType" eType="#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="channelBehavior" eType="ecore:EClass ../../de.dlr.sc.virsat.model.ext.tml.behavioral/concept/concept.ecore#//ChannelBehavior"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataType" eSuperTypes="../../de.dlr.sc.virsat.model/model/dvlm.ecore#//dmf/DObject #//IType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstractType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serializedDefinition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="../../de.dlr.sc.virsat.model/model/dvlm.ecore#//dmf/DObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeOf" eType="#//IType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dimensions" upperBound="-1"
        eType="#//ArrayDimension" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceFrame" eType="#//ReferenceFrameDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeUnit" eType="#//UnitDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isConst" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueLiteral" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxValueLiteral" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minValueLiteral" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayDimension" eSuperTypes="../../de.dlr.sc.virsat.model/model/dvlm.ecore#//dmf/DObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enumeration" eSuperTypes="../../de.dlr.sc.virsat.model/model/dvlm.ecore#//dmf/DObject #//IType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literals" upperBound="-1"
        eType="#//EnumerationLiteral" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serializedDefinition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnumerationLiteral" eSuperTypes="../../de.dlr.sc.virsat.model/model/dvlm.ecore#//dmf/DObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyNum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
